# Generated by Django 6.0.8 on 2026-09-15 23:29

from django.conf import settings
from django.db import migrations, models


def migrate_roles_and_validate_users(apps, schema_editor):
    Membership = apps.get_model("core", "Membership")
    Membership.objects.filter(role__in=["owner", "manager"]).update(
        role="communications_manager"
    )
    Membership.objects.filter(role="contributor").update(
        role="communications_officer"
    )
    duplicate = (
        Membership.objects.values("user_id")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
        .order_by("user_id")
        .first()
    )
    if duplicate:
        raise RuntimeError(
            "Cannot enforce one membership per user while duplicate memberships exist."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calendarevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_roles_and_validate_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('communications_manager', 'Communications Manager'), ('communications_officer', 'Communications Officer'), ('support_staff', 'Support Staff'), ('intern', 'Intern'), ('viewer', 'Viewer')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user',), name='one_membership_per_user'),
        ),
    ]
