# Generated by Django 6.0.8 on 2026-09-15 23:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_existing_profiles(apps, schema_editor):
    Membership = apps.get_model("core", "Membership")
    StaffProfile = apps.get_model("accounts", "StaffProfile")
    StaffProfile.objects.bulk_create(
        StaffProfile(membership_id=membership_id)
        for membership_id in Membership.objects.values_list("id", flat=True)
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_membership_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(blank=True, max_length=160)),
                ('job_title', models.CharField(blank=True, max_length=160)),
                ('job_group', models.CharField(blank=True, max_length=100)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('job_description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='core.membership')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_profiles', to='core.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('communications_manager', 'Communications Manager'), ('communications_officer', 'Communications Officer'), ('support_staff', 'Support Staff'), ('intern', 'Intern'), ('viewer', 'Viewer')], max_length=32)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to='core.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'email'], name='accounts_in_organiz_a2b374_idx')],
            },
        ),
        migrations.RunPython(create_existing_profiles, migrations.RunPython.noop),
    ]
